//GET http://localhost:9000/products HTTP/1.1
GET http://localhost:9000/subcategory HTTP/1.1
POST http://localhost:9000/products HTTP/1.1
Content-Type: application/json

{

    "title":"test",
    "description":"description",
    "place":"teste",
    "state":"ixelles",
    "subcategory":"subcategory"

}