# POST https://pfe-vinci-market.herokuapp.com/pictures HTTP/1.1
# Content-Type: application/json

# {
#     "idProduct":"61b883852903b511eec43f48",
#     "namePicture":"machin"
# }

GET  https://pfe-vinci-market.herokuapp.com/pictures/61bb7ad4dfc8ff3d86f5893b HTTP/1.1

POST https://pfe-vinci-market.herokuapp.com/pictures HTTP/1.1
Content-Type: application/json

{
    "idProduct":"61bb7ad4dfc8ff3d86f5893b",
    "nameVideo":"machin.mp4"
}