# POST https://pfe-vinci-market.herokuapp.com/pictures HTTP/1.1
# Content-Type: application/json

# {
#     "idProduct":"61b883852903b511eec43f48",
#     "namePicture":"machin"
# }

GET  https://pfe-vinci-market.herokuapp.com/videos/61b9cda2234234528fbaea0f HTTP/1.1

POST https://pfe-vinci-market.herokuapp.com/videos HTTP/1.1
Content-Type: application/json

{
    "idProduct":"61b9cda2234234528fbaea0f",
    "nameVideo":"machin.mp4"
}