//GET http://localhost:8080/users HTTP/1.1


# POST http://localhost:9000/users HTTP/1.1 
# Content-Type:application/json

# {
    
        
#         "lastName":"test",
#         "firstName":"teste",
#         "password":"teste",
#         "campus":"ixelles",
#         "phone":"5456",
#         "mail":"merin.duvivier@student.vinci.be",
#         "isAdmin":false
    
    
# }

//GET http://localhost:8080/users/user/61b0aa3f5dc8e3107ab1467a HTTP/1.1


PUT http://localhost:9000/users/61b627ceaada2474e6085de2 HTTP/1.1 
Content-Type:application/json

 {

         "idUser":"61b627ceaada2474e6085de2",
         "lastName":"aragorn",
         "firstName":"yolo",
         "password":"test",
         "campus":"ixelles",
         "phone":"151812626216",
         "mail":"93sfervnr@student.vinci.be",
         "isAdmin":false
    
 }