version: 2

jobs:
    build:
        # The primary container is an instance of the first list image listed. Your build commands run in this container.
        docker:
            - image: cimg/node:16.13.1-browsers
        steps:     
            - checkout
            - run:
                name: Install node_modules with npm
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: Install npm
                command: sudo npm install -g npm@latest
            #- run:
                #name: Install ng common (npm part for angular)
                #command: sudo apt install ng-common -y
            - run: 
                name: Install angularcli
                command: sudo npm install -g @angular/cli@latest


