version: 2.1

orbs:
heroku: circleci/heroku@2.1
jobs:
    build:
        # The primary container is an instance of the first list image listed. Your build commands run in this container.
        docker:
            - image: cimg/node:16.13.1-browsers
        steps:     
            - checkout
            - run:
                name: Install node_modules with npm
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: Install npm
                command: sudo npm install -g npm@latest
            #- run:
                #name: Install ng common (npm part for angular)
                #command: sudo apt install ng-common -y
            - run: 
                name: Install angularcli
                command: sudo npm install -g @angular/cli@latest
workflows:      
heroku_deploy:
    jobs:
    - build
    - heroku/deploy-via-git:
        requires:
            - build # only run deploy-via-git job if the build job has completed
        filters:
            branches:
            only: main # only run deploy-via-git job on main branch
    -run:
        name: launch prod
        command: ng serve --configuration=production
